In [4]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [5]:
# 파이썬 리스트 선언
data = [1, 2, 3, 4, 5]
data, type(data)

([1, 2, 3, 4, 5], list)

In [6]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [[1,2,3],
        [4,5,6],
        [7,8,9]]
data2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
# 파이썬 list를 numpy array로 변환합니다.
arr1 = np.array(data)
arr1, type(arr1)  #
# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
# np.array.shape은 np.array의 크기를 알려줍니다.
arr1.shape
# 5 x 1


(5,)

In [10]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print(arr2.shape)
print('arr의 차원 : ',arr2.ndim)   # arr2의 차원

print('arr2의 행, 열 크기 :', arr2.shape)  # arr2의 행, 열의 크기

print('arr2의 크기 : ', arr2.size)        # arr2의 행 x 열

print('arr2의 datatype : ', arr2.dtype)
# arr2의 원소의 타입. # int64 : integer + 64bits

print('arr2의 원소의사이즈', arr2.itemsize)
# arr2의 원소의 사이즈(bytes) # 64bits = 8B

print('arr2의 nbytes : ', arr2.nbytes)
# itemsize * size # numpy array가 차지하는 메모리 공간.

(3, 3)
arr의 차원 :  2
arr2의 행, 열 크기 : (3, 3)
arr2의 크기 :  9
arr2의 datatype :  int32
arr2의 원소의사이즈 4
arr2의 nbytes :  36


In [13]:
# 0이 5개 있는 array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
# 0이 5개 있는 array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
# 1이 3개 있는 array
np.ones(3)

array([1., 1., 1.])

In [16]:
# 1이 2x2인 array
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [17]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# 10부터 99까지 숫자를 자동으로 생성한 array
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [19]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array((1, 2, 3))
v2 = np.array((4, 5, 6))
type(v1), type(v2)

(numpy.ndarray, numpy.ndarray)

In [20]:
# 리스트로 더하기 연산해보기
t1 = (1, 2, 3)
t2 = (4, 5, 6)
t1 + t2

(1, 2, 3, 4, 5, 6)

In [21]:
#  vector addition
v1 + v2

array([5, 7, 9])

In [22]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [23]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [24]:
# (not vector operation) elementwise division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [25]:
# dot product
v1 @ v2   # 1x4 + 2x5 + 3x6 = 32

32

## Brodcast

In [26]:
arr1 = np.array([[1, 2, 3],
               [4, 5, 6]])

In [27]:
arr1.shape

(2, 3)

In [28]:
arr2 = np.array([7, 8, 9])

In [29]:
arr2.shape

(3,)

In [30]:
# 2개의 array를 더해보면?
arr1 + arr2            #[1, 2, 3] + [7, 8, 9] // [4, 5, 6] + [7, 8, 9]

array([[ 8, 10, 12],
       [11, 13, 15]])

In [31]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2           # [1, 2, 3] * [7, 8, 9] // [4, 5, 6] * [7, ,8, 9]

# [1, 2, 3] x [7]
#[4, ,5, 6]   [8]
#            [9]


array([[ 7, 16, 27],
       [28, 40, 54]])

In [32]:
# arr1에 10을 곱해보면?
arr1 *10          

array([[10, 20, 30],
       [40, 50, 60]])

In [33]:
# arr1을 제곱해보면?
arr1 * arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

## Universal Functions

In [34]:
arr1 = np.array([1, 2, 3])
arr1 / 1            #데이터 타입 변경

array([1., 2., 3.])

In [35]:
# 모든 원소를 역수를 취하려면 어떻게 해야할까?
1 / arr1

array([1.        , 0.5       , 0.33333333])

In [36]:
# 모든 원소에 2를 더하려면 어떻게 해야할까?
arr1 + 2

array([3, 4, 5])