In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [4]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [5]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [6]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [7]:
x[0] + x[1]

3.0

In [14]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [15]:
x[0] + x[1]

'12'

In [27]:
import warnings
warnings.filterwarnings("ignore")

In [28]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

In [29]:
np.log(0)

-inf

In [19]:
np.exp(-np.inf)

0.0

In [30]:
a = np.zeros(5)

In [31]:
a

array([0., 0., 0., 0., 0.])

In [32]:
b = np.zeros((2,3 ))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
c = np.zeros((5, 2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [34]:
d = np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [35]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCD'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [36]:
e = np.ones((2, 3, 4), dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [37]:
f = np.ones_like(b, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [38]:
g = np.empty((4, 3))

In [39]:
g

array([[6.68281924e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 7.56587583e-307, 2.16537642e+184],
       [7.16475257e-038, 1.81789397e+185, 1.43764846e-051],
       [1.40509796e+165, 4.99993560e+174, 3.83841686e+175]])

In [40]:
np.arange(10)              # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(3, 21, 2)        # 시작, 끝 (포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
np.linspace(0, 100, 5)     #시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [43]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [44]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a.reshape(2, 3, -1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [50]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [51]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [55]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [56]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [57]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [58]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [60]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [61]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [69]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [70]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [71]:
c. shape

(2, 3, 4)

In [72]:
c = np.stack([c1, c2], axis=1)

In [73]:
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [74]:
c.shape

(3, 2, 4)

In [75]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [76]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [79]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])