In [2]:
import numpy as np

In [3]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [4]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 3.87 ms


In [5]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [6]:
%%time
z = x + y

Wall time: 1.44 ms


In [7]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [9]:
a == b

array([False,  True, False,  True])

In [10]:
a >= b

array([False,  True,  True,  True])

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [12]:
np.all(a == b)

False

In [13]:
np.all(a == c)

True

In [14]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [16]:
10**a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [17]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [20]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [22]:
x = np.arange(5)

In [23]:
x

array([0, 1, 2, 3, 4])

In [24]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [25]:
x + y

array([1, 2, 3, 4, 5])

In [26]:
x + 1

array([1, 2, 3, 4, 5])

In [28]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [30]:
y = np.arange(5)[:,np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [31]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [32]:
y = np.arange(3)
y

array([0, 1, 2])

In [33]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [34]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [35]:
np.sum(x)

10

In [36]:
x.sum(0)

10

In [37]:
x = np.array([1, 2, 3])

In [38]:
x.min()

1

In [39]:
x.max()

3

In [40]:
x.argmin()      # 최솟값의 위치

0

In [41]:
x.argmax()      # 최댓값의 위치

2

In [42]:
x = np.array([1, 2, 3, 1])

In [43]:
x.mean()

1.75

In [44]:
np.median(x)

1.5

In [45]:
np.all([True, True, False])

False

In [46]:
np.any([True, True, False])

True

In [48]:
import warnings
warnings.filterwarnings("ignore")

In [49]:
a = np.zeros((100, 100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [50]:
np.any(a != 0)

False

In [51]:
np.all(a == a)

True

In [52]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [53]:
((a <= b) & (b <= c)).all()

True

In [54]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [55]:
x.sum()

6

In [56]:
x.sum(axis=0)      # 열 합계

array([3, 3])

In [57]:
x.sum(axis=1)     # 행 합계

array([2, 4])

In [60]:
a = np.array([[4, 3, 5, 7],
             [1, 12, 11, 9],
             [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [61]:
np.sort(a)       # axis = -1 또는 axis = 1 과 동일 행 정렬

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [62]:
np.sort(a, axis=0)       #열 정렬

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [63]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [64]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [65]:
a[j]

array([12, 25, 38, 42])

In [66]:
np.sort(a)

array([12, 25, 38, 42])