In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [5]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [7]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [8]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [10]:
np.random.rand(0)

array([], dtype=float64)

In [11]:
np.random.rand(5)

array([0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194])

In [12]:
np.random.rand(10)

array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ])

In [13]:
np.random.rand(10)

array([0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077])

In [14]:
np.random.rand(10)

array([0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
       0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559])

In [15]:
x = np.arange(10)

In [16]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.random.shuffle(x)
x

array([2, 4, 6, 3, 9, 1, 0, 8, 5, 7])

## numpy.random.choice(a, size=None, replace=True, p=None)
a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성

size : 정수. 샘플 숫자

replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능

p : 배열. 각 데이터가 선택될 수 있는 확률

In [22]:
np.random.choice(5, 5, replace=False)   #shuffle 명령과 같다. 

array([3, 1, 0, 4, 2])

In [19]:
np.random.choice(5, 3, replace=False)   # 3개만 선택

array([3, 4, 1])

In [20]:
np.random.choice(5, 10)                  # 반복해서 10개 선탣

array([2, 2, 0, 1, 0, 2, 2, 3, 2, 3])

In [21]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  
                                              # 선책 확률을 다르게 해서 10개 선택

array([2, 2, 3, 0, 3, 3, 2, 3, 0, 3])

In [23]:
np.random.rand(10)

array([0.84234208, 0.64717414, 0.84138612, 0.26473016, 0.39782075,
       0.55282148, 0.16494046, 0.36980809, 0.14644176, 0.56961841])

In [24]:
np.random.rand(3, 5)

array([[0.70373728, 0.28847644, 0.43328806, 0.75610669, 0.39609828],
       [0.89603839, 0.63892108, 0.89155444, 0.68005557, 0.44919774],
       [0.97857093, 0.11620191, 0.7670237 , 0.41182014, 0.67543908]])

In [25]:
np.random.randn(10)

array([-0.82097758, -1.09974201,  0.08672983,  0.45628701,  0.4310333 ,
        2.07257353, -0.53778512, -1.3784301 , -0.49240425,  2.32773811])

In [26]:
np.random.randn(3, 5)

array([[ 1.80440397, -0.24942133, -0.82086383, -1.49333996,  0.52417595],
       [ 0.34511317,  0.72437468, -2.04038084, -1.0797781 , -0.69342441],
       [-2.33804615,  1.66226234, -0.27535274, -0.74657045,  1.22510346]])

In [27]:
np.random.randint(10, size=10)

array([8, 2, 3, 9, 7, 5, 3, 4, 5, 3])

In [28]:
np.random.randint(10, 20, size=10)

array([13, 17, 19, 19, 19, 17, 13, 12, 13, 19])

In [30]:
np.random.randint(10, 20, size=(3, 5))

array([[17, 17, 15, 11, 12],
       [12, 18, 11, 15, 18],
       [14, 10, 12, 15, 15]])