In [17]:
import numpy as np
import pandas as pd

from sklearn.decomposition import PCA

In [15]:
np.random.seed(4)
m = 60
w1, w2 = 0.1, 0.3
noise = 0.1

angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m, 3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)

print('X.shape:', X.shape)

X.shape: (60, 3)


In [16]:
df = pd.DataFrame(X, columns=['$X_1$', '$X_2$', '$X_3$'])
df.head(10)

$X_1$     $X_2$     $X_3$
0 -1.015700 -0.550913 -0.261326
1 -0.007717  0.599586  0.035078
2 -0.953171 -0.464537 -0.249203
3 -0.920123  0.210096  0.021824
4 -0.763097  0.158261  0.191525
5  1.118161  0.325087  0.317106
6 -1.022589 -0.643841 -0.133687
7  0.673520 -0.273425 -0.007878
8  1.016196  0.515466  0.467833
9  0.549577  0.677280  0.234016

In [18]:
pca = PCA(n_components=3)
pca.fit(X)

PCA(n_components=3)

In [19]:
print('singular value :', pca.singular_values_)
print('singular vector :\n', pca.components_.T)

singular value : [6.77645005 2.82403671 0.78116597]
singular vector :
 [[-0.93636116  0.34027485 -0.08626012]
 [-0.29854881 -0.90119108 -0.31420255]
 [-0.18465208 -0.2684542   0.94542898]]


In [20]:
print('eigen_value :', pca.explained_variance_)
print('explained variance ratio :', pca.explained_variance_ratio_)

eigen_value : [0.77830975 0.1351726  0.01034272]
explained variance ratio : [0.84248607 0.14631839 0.01119554]


In [21]:
print('explained variance ratio :', pca.explained_variance_ratio_)

explained variance ratio : [0.84248607 0.14631839 0.01119554]


In [22]:
print('explained variance ratio :', pca.explained_variance_ratio_)


explained variance ratio : [0.84248607 0.14631839 0.01119554]


In [23]:
pca = PCA(n_components=0.95)
X_proj = pca.fit_transform(X)

print('principal component vec :\n', pca.components_.T)

principal component vec :
 [[-0.93636116  0.34027485]
 [-0.29854881 -0.90119108]
 [-0.18465208 -0.2684542 ]]
